version: '3.7'

services:
  # ------------------------------------------------------------------
  # Postgres (metastore + data mart)
  # ------------------------------------------------------------------
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"        # ← exposed to host so dbt can reach it
    restart: always

  # ------------------------------------------------------------------
  # Redis (Celery broker)
  # ------------------------------------------------------------------
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  # ------------------------------------------------------------------
  # Airflow webserver
  # ------------------------------------------------------------------
  airflow-webserver:
    image: apache/airflow:2.5.1
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "dbt-core dbt-postgres psycopg2-binary"
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: webserver
    restart: always

  # ------------------------------------------------------------------
  # Airflow scheduler
  # ------------------------------------------------------------------
  airflow-scheduler:
    image: apache/airflow:2.5.1
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "dbt-core dbt-postgres psycopg2-binary"
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt
    command: scheduler
    restart: always

  # ------------------------------------------------------------------
  # Airflow worker (Celery)
  # ------------------------------------------------------------------
  airflow-worker:
    image: apache/airflow:2.5.1
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "dbt-core dbt-postgres psycopg2-binary"
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt
    command: celery worker
    restart: always

# --------------------------------------------------------------------
# Named volumes
# --------------------------------------------------------------------
volumes:
  postgres_data:
